apiVersion: v1
kind: Secret
metadata:
  name: ca-cert
type: Opaque
data:
  # These values will need to be replaced with base64-encoded certificates
  # Use: cat certs/ca/ca.crt | base64 | tr -d '\n'
  ca.crt: '${CA_CERT}'
---
apiVersion: v1
kind: Secret
metadata:
  name: api-service-certs
type: Opaque
data:
  # These values will need to be replaced with base64-encoded certificates
  api-service.crt: '${API_SERVICE_CERT}'
  api-service.key: '${API_SERVICE_KEY}'
---
apiVersion: v1
kind: Secret
metadata:
  name: client-service-certs
type: Opaque
data:
  # These values will need to be replaced with base64-encoded certificates
  client-service.crt: '${CLIENT_SERVICE_CERT}'
  client-service.key: '${CLIENT_SERVICE_KEY}'
